name: Video Engine Stealth
on:
  workflow_dispatch:
    inputs:
      video_url:
        required: true
      quality:
        default: '1080'

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Stealth Setup
        run: |
          python3 -m pip install --upgrade yt-dlp
          
      - name: Fetch Video Data
        run: |
          # Bot bypass karne ke liye generic user-agent aur certificates ignore kiye hain
          yt-dlp --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          --no-check-certificates \
          --prefer-free-formats \
          -f "bestvideo[height<=${{ github.event.inputs.quality }}]+bestaudio/best" \
          --get-url "${{ github.event.inputs.video_url }}"
